spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true 
server:
  port: 3001
  
eureka:
  client:
    service-url:  #注册eureka
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#代理转发的路由规则
#默认路由规则  可以不配置    会从eureka注册中心配置服务器
zuul:
  retryable: true #启用重试
  routes:
    item-service: /item-service/**    #路径  **所有子路径
    user-service: /user-service/**
    order-service: /order-service/**

#整合ribbon
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1  #默认0
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500 #hystrix超时 降级
  
#暴露 hystrix.stream 监控端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  